DROP TABLE IF EXISTS COUNTER;
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS FACULTIES CASCADE;
DROP TABLE IF EXISTS LOSTSTUFF;
DROP TABLE IF EXISTS FOUNDSTUFF;
DROP TABLE IF EXISTS GAMEFRIEND;
DROP TABLE IF EXISTS DATASHAREDHOUSE CASCADE;
DROP TABLE IF EXISTS DATASEARCHEDHOUSE CASCADE;
DROP TABLE IF EXISTS RESTAURANTS CASCADE;
DROP TABLE IF EXISTS CAMPUSLOCATIONS CASCADE;
DROP TABLE IF EXISTS RESTAURANTMENUS CASCADE;
DROP TABLE IF EXISTS SPECIALTUTORS;
DROP TABLE IF EXISTS SPECIALSTUDENTS;
DROP TABLE IF EXISTS CLUBACTIVITIES;
DROP TABLE IF EXISTS ITUACTIVITIES;
DROP TABLE IF EXISTS SPORTACTIVITIES;
DROP TABLE IF EXISTS SHAREDBOOKS;
DROP TABLE IF EXISTS SHAREDLESSONNOTES;


CREATE TABLE COUNTER (N INTEGER);


INSERT INTO COUNTER (N) VALUES (0);


CREATE TABLE FACULTIES (
    ID SERIAL PRIMARY KEY NOT NULL,
    FACULTYNAME VARCHAR(30) NOT NULL,
    FACULTYCODE VARCHAR(30) NOT NULL
);

CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(500) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    SURNAME VARCHAR(30) NOT NULL,
    FACULTYID INTEGER REFERENCES FACULTIES(ID)
);


INSERT INTO FACULTIES(FACULTYNAME, FACULTYCODE) VALUES ('ComputerAndInformaticsFaculty', 'BLG');
INSERT INTO USERS(USERNAME, PASSWORD, EMAIL, NAME, SURNAME, FACULTYID) VALUES ('admin', '$6$rounds=656000$NhjGHwap0iYnsrNW$Y0sK0vHaShrBy0Q62GN3TIMQFdcDV7u98tjntyJUfN4EzDGKCr28UaG838uHaRNVCATFomj.d6gc.a1107lZm1', 'admin@gmail.com', 'server', 'admin', 1);





CREATE TABLE SHAREDBOOKS(
    ID SERIAL PRIMARY KEY NOT NULL ,
    NAMEOFBOOK VARCHAR(100) NOT NULL ,
    LESSONNAME VARCHAR(50) NOT NULL ,
    LESSONCODE VARCHAR(50) NOT NULL ,
    TYPEOFSHARE VARCHAR(80) NOT NULL ,
    PRICE INTEGER,
    USERID INTEGER REFERENCES USERS(ID)
);

CREATE TABLE SHAREDLESSONNOTES(
  ID SERIAL PRIMARY KEY NOT NULL,
  NAMEOFNOTES VARCHAR(100) NOT NULL,
  LESSONNAME VARCHAR(50) NOT NULL ,
  LESSONCODE VARCHAR(50) NOT NULL ,
  TEACHERNAME VARCHAR(100) NOT NULL ,
  USERID INTEGER REFERENCES USERS(ID)
);

CREATE TABLE LOSTSTUFF (
    ID SERIAL PRIMARY KEY NOT NULL,
    STUFFDESC VARCHAR(300) NOT NULL,
    POSSIBLELOC VARCHAR(50) NOT NULL,
    POSSIBLEDATE DATE NOT NULL,
    OWNERNAME VARCHAR(50) NOT NULL,
    OWNERMAIL VARCHAR(50) NOT NULL,
    OWNERPHONE VARCHAR(15) NOT NULL,
    USERID INTEGER REFERENCES USERS(ID)
);


--INSERT INTO LOSTSTUFF(STUFFDESC, POSSIBLELOC, POSSIBLEDATE, OWNERNAME, OWNERMAIL, OWNERPHONE) VALUES ('KAYIP', 'MED', '2017-10-13', 'Sercan', 'sahanse@itu.edu.tr', '+905350000000');


CREATE TABLE FOUNDSTUFF (
    ID SERIAL PRIMARY KEY NOT NULL,
    STUFFDESC VARCHAR(300) NOT NULL,
    CURRENTLOC VARCHAR(50) NOT NULL,
    FINDINGDATE DATE NOT NULL,
    FOUNDERNAME VARCHAR(50) NOT NULL,
    FOUNDERMAIL VARCHAR(50) NOT NULL,
    FOUNDERPHONE VARCHAR(15) NOT NULL,
    USERID INTEGER REFERENCES USERS(ID)
);


--INSERT INTO FOUNDSTUFF(STUFFDESC, CURRENTLOC, FINDINGDATE, FOUNDERNAME, FOUNDERMAIL, FOUNDERPHONE) VALUES ('KAYIP', 'MED', '2017-10-13', 'Sercan', 'sahanse@itu.edu.tr', '+905350000000');


CREATE TABLE GAMEFRIEND(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(80) NOT NULL,
    TYPE VARCHAR(30) NOT NULL,
    GAMEDATE DATE,
    LOCATION VARCHAR(80),
    PLAYERNUMBER INTEGER,
    DESCRIPTION VARCHAR(120)
);


INSERT INTO GAMEFRIEND (NAME, TYPE, GAMEDATE, LOCATION, PLAYERNUMBER, DESCRIPTION)
                                VALUES('Batak', 'Table Game', '2017-10-13', 'MED', 4, 'Come with your couple');


CREATE TABLE DATASHAREDHOUSE(
    ID SERIAL PRIMARY KEY NOT NULL,
    LOCATION VARCHAR(80) NOT NULL,
    RENTPRICE INTEGER NOT NULL,
    NUMBEROFPEOPLE INTEGER NOT NULL,
    NUMBEROFROOM VARCHAR (10) NOT NULL,
    DESCRIPTION VARCHAR (300) NOT NULL,
    USERID INTEGER REFERENCES USERS(ID)
);


--INSERT INTO DATASHAREDHOUSE(LOCATION, RENTPRICE, NUMBEROFPEOPLE,NUMBEROFROOM,DESCRIPTION,GENDER) VALUES ('Levent', '1500', '2','3+1','aa','Male' );

CREATE TABLE DATASEARCHEDHOUSE(
    ID SERIAL PRIMARY KEY NOT NULL,
    LOCATION VARCHAR(80) NOT NULL,
    MINRENTPRICE INTEGER NOT NULL,
    MAXRENTPRICE INTEGER NOT NULL,
    DESCRIPTION VARCHAR (300) NOT NULL,
    USERID INTEGER REFERENCES USERS(ID)
);

--INSERT INTO DATASEARCHEDHOUSE(LOCATION, MINRENTPRICE, MAXRENTPRICE,DESCRIPTION,NUMBEROFROOMS,GENDER) VALUES ('Levent', '300', '500', 'aa','3+1','Male' );

CREATE TABLE CAMPUSLOCATIONS (
    ID SERIAL PRIMARY KEY NOT NULL,
    CAMPUSNAME  VARCHAR(50) NOT NULL,
    CAMPUSDISTRICT VARCHAR(50) NOT NULL
);

CREATE TABLE RESTAURANTMENUS (
    ID SERIAL PRIMARY KEY NOT NULL,
    FOODTYPE  INTEGER NOT NULL,
    FOODNAME VARCHAR(40) NOT NULL,
    FOODPRICE FLOAT NOT NULL
);

CREATE TABLE RESTAURANTS (
    ID SERIAL PRIMARY KEY NOT NULL,
    LOCATIONID INTEGER REFERENCES CAMPUSLOCATIONS(ID) NOT NULL,
    MENUTYPE INTEGER NOT NULL,
    MENUID INTEGER REFERENCES RESTAURANTMENUS(ID) NOT NULL,
    RESTAURANTPOINT INTEGER NOT NULL,
    PRICEBALANCE INTEGER NOT NULL,
    OPENINGTIME TIME  NOT NULL,
    CLOSINGTIME TIME NOT NULL,
    SERVICETYPE VARCHAR(20) NOT NULL
);

CREATE TABLE SPECIALTUTORS (
    ID SERIAL PRIMARY KEY NOT NULL,
    SUBJECT VARCHAR(20) NOT NULL,
    FULLNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    PHONENUMBER VARCHAR(15) NOT NULL,
    USERID INTEGER REFERENCES USERS(ID)
);

CREATE TABLE SPECIALSTUDENTS (
    ID SERIAL PRIMARY KEY NOT NULL,
    SUBJECT VARCHAR(20) NOT NULL,
    FULLNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    PHONENUMBER VARCHAR(15) NOT NULL,
    USERID INTEGER REFERENCES USERS(ID)
);

CREATE TABLE CLUBACTIVITIES (
    ID SERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(40) NOT NULL,
    CLUBNAME VARCHAR(40) NOT NULL,
    ACTIVITYDATE DATE NOT NULL,
    ACTIVITYTIME TIME NOT NULL,
    LOCATION VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(80),
    USERID INTEGER REFERENCES USERS(ID)
);


CREATE TABLE SPORTACTIVITIES (
    ID SERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(40) NOT NULL,
    SPORTNAME VARCHAR(40) NOT NULL,
    ACTIVITYDATE DATE NOT NULL,
    ACTIVITYTIME TIME NOT NULL,
    LOCATION VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(80),
    USERID INTEGER REFERENCES USERS(ID)
);


CREATE TABLE ITUACTIVITIES (
    ID SERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(40) NOT NULL,
    SPECIALPARTICIPANT VARCHAR(40) NOT NULL,
    ACTIVITYDATE DATE NOT NULL,
    ACTIVITYTIME TIME NOT NULL,
    LOCATION VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(80),
    USERID INTEGER REFERENCES USERS(ID)
);


